### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [MaxVerevkin/wayrs#19]
Regressed by d142fc7ad29e

```rust
$ cargo build --target x86_64-unknown-freebsd
[...]
error[E0308]: mismatched types
  --> wayrs-core/src/transport/unix.rs:45:34
   |
45 |                 pmhdr.cmsg_len = unsafe { libc::CMSG_LEN(fds_size as libc::c_uint) } as usize;
   |                 --------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `usize`
   |                 |
   |                 expected due to the type of this binding
```

**Comment by MaxVerevkin** [comment]
Fixed in https://github.com/MaxVerevkin/wayrs/commit/bb652afd6e2211e9b52eb07ea44a6b30641e9d00
